### ISSUE TITLE
Not works! :(

### ISSUE THREAD

**Issue by maitret** [rehy/cordova-plugin-calltrap#1]
Testing with PhoneGapBuild: `<plugin name="cordova-plugin-calltrap" source="npm" />`

Android: 5.1

Code:
`CallTrap.onCall(function(state){
$(".state_phone").append("<br>Estatus: "+state+"");
console.log("CHANGE STATE: ${state}");
  switch (state) {
    case CallTrap.STATE.RINGING:
      console.log('Phone is ringing')
      break;
    case CallTrap.STATE.OFFHOOK:
      console.log('Phone is off-hook')
      break;
    case CallTrap.STATE.IDLE:
      console.log('Phone is idle')
      break;
  }
});`

**Comment by ratson** [comment]
Which part is not working? Do you see errors? e.g. `CallTrap` is not defined.

Please be reminded the app need to be run on background in order to work.

**Comment by ratson** [comment]
@maitret Did you register the callback after `deviceready` event? I have updated the README to mention this requirement.

I have it working for my project, I need more information to help. It would be great if you could create a failing project that I could try.

**Comment by ratson** [comment]
@maitret Since I am not hearing your feedback, I am closing this.

**Comment by maitret** [comment]
How implement this?

You provide a example?... Please :(
